### ISSUE TITLE
Pascal case for query methods

### ISSUE THREAD

**Issue by alexeygolev** [fauna/faunadb-js#100]
Is there any particular reason for pascal case in query methods? Normally one would assume pascal case signifies a class/constructor function (in fact `faunadb.Client` is indeed a class called with `new`) which can be confusing. Another con is that in case of `Map` you can't do
```js
import { Client, query } from 'fauna'
const { Map } = query
```

**Comment by erickpintor** [comment]
We're making an effort to unify our query language syntax across all drivers in order to give users a seamless transition between different tech stacks. 

We found pascal case the one that conflicts less with existing native structures across the languages we support. Therefore, we're using pascal case where we can, unless is highly discouraged by the community. Ruby and Python drivers are currently using snake case, for example, but some methods must have suffixes like `if_` and `class_`.

Query methods end up being `Expr` constructors. We thought that pascal case would still be a fit in that case.

**Comment by alexeygolev** [comment]
@erickpintor I think idiomatic language use would be a better fit for a seamless transition than a unified syntax. I found the current `Ruby` driver better in this sense. It feels like Ruby. JavaScript doesn't feel like javascript at all (don't get me wrong — I'm talking about conventions used, not the actual functionality of the driver which is very impressive).
As I pointed out `Map` clashes with native Map so you can't do `const { Map } = query`. It's not a show stopper but it's an annoyance that you might want to avoid having in the driver before Fauna hits a public release.
And technically query methods are not constructors. In idiomatic JS constructors are called with the `new` keyword. Query methods are factories and factories are camel case in JS. 
Rethink has an official driver with 20,040 npm installs and rethinkdbdash with 20,272 installs. The main benefit of the unofficial one is that it uses promises vs callbacks in the official one. And the obvious problem is that if half of your community uses the unofficial driver changing the underlying protocol is harder. That's the only reason I'm raising this issue. There are still going to be unofficial drivers. But if you go with idiomatic JS there will be 50 of them not 200.

**Comment by erickpintor** [comment]
@alexeygolev have you found anything else that you would consider non-idiomatic JS? Or is it just the query language functions?

**Comment by alexeygolev** [comment]
@erickpintor Everything else seems to be perfect.

**Comment by jchris** [comment]
My default linter didn't like uppercase functions without new either...

**Comment by sprsquish** [comment]
Internally, the final decision on this is to unify the feel of the drivers across languages. That will come at the expense of being idiomatic.
