### ISSUE TITLE
Could q.Lambda generate q.Let bindings as well ?

### ISSUE THREAD

**Issue by guillaumervls** [fauna/faunadb-js#228]
Hi,

Currently, `q.Lambda` takes a function argument, which is more convenient, and takes care of the transformation of its arguments into `q.Var` where they are used. Nice.

But if you use a statement like `const x = anExpression` in the function body, in the output, `x` just gets replaced everywhere it's used by `anExpression`. Could the driver generate a `q.Let` (and `q.Var`s) call instead?

This would have the advantage of a better legibility ; and also not to compute `anExpression` multiple times on the DB server (unless it's already optimized for that...).

Cheers!

**Comment by marrony** [comment]
@guillaumervls in order to do this we would need to parse the function body and re-write its AST to introduce `Let` on variable assignments, I don't see an easy/consistent way of doing this, do you know any library capable of parse js to an AST?

**Comment by guillaumervls** [comment]
@marrony I know some of the most popular JS AST parsers like https://babeljs.io/docs/en/next/babel-parser.html or https://github.com/acornjs/acorn. They are widely used because JS is transpiled a lot (e.g. to use new language features on older browsers or build DSL like React's JSX...). But I never used them directly myself, so I'm afraid I won't be able to help much...

**Comment by marrony** [comment]
@guillaumervls I took a look on those parsers, and looks like this is not the path we want to take. Rewrite the AST will bring a lot of complications to the driver because JS has many constructions FQL doesn't have, like do/while/for, also and given FQL follows a functional approach, all functions/lambdas must have a single point of return, and JS allows many, branching is another point of complication. If you want to give it a try, feel free to open a PR and we can analyze, currently we doesn't have bandwidth to implement such feature in the correct way.

**Comment by fauna-ryanharris** [comment]
@guillaumervls Closing this out based on @marrony's latest comment 👍
