### ISSUE TITLE
q.Lambda behaves differently depending on the number of arguments

### ISSUE THREAD

**Issue by guillaumervls** [fauna/faunadb-js#229]
Hi,

Currently:
`q.Lambda(foo => foo)` generates `Lambda("foo", Var("foo"))`
`q.Lambda((foo, bar) => foo)` generates `Lambda(["foo", "bar"], Var("foo"))`

As `Lambda("foo", Var("foo"))` and `Lambda(["foo"], Var("foo"))` are not the same, shouldn't it be more coherent to have `q.Lambda(foo => foo)` generates `Lambda(["foo"], Var("foo"))` then ?

Cheers!

PS: Context: It made me struggle about why my grapghQL custom resolver with a single argument was not working, whereas with multiple ones it worked.

**Comment by BrunoQuaresma** [comment]
Thanks @guillaumervls ! Taking a look with the team.

**Comment by parkhomenko** [comment]
Sorry for the late reply.
I wanted to provide more details about this issue.

The steps I did to replicate it:
1. I have created 3 UDFs in the fauna dashboard:
```
// Function that takes a single input parameter
CreateFunction({
  name: "increment",
  body: Query(
    Lambda("param1", Add(1, Var("param1")))
  )
})

// The same as above but this single parameter is wrapped as an array
CreateFunction({
  name: "incrementArray",
  body: Query(
    Lambda(["param1"], Add(1, Var("param1")))
  )
})

// Function with 2 input parameters
CreateFunction({
  name: "addition",
  body: Query(
    Lambda(["param1", "param2"], Add(Var("param1"), Var("param2")))
  )
})
```
2. Next step was creating a GraphQL schema for all those functions (I used the custom resolver Fauna feature here):
```
type Query {
    increment(param1: Int): Int! @resolver(name: "increment")
    incrementArray(param1: Int): Int! @resolver(name: "incrementArray")
    addition(param1: Int, param2: Int): Int! @resolver(name: "addition")
}
```
3. Calling functions “incrementArray” and “addition” worked fine from Fauna GraphQL playground and from javascript client code:
```
const query = gql`
        {
            incrementArray(param1: 5)
        }
    `
apolloClient.query({query}).then(results => {
    console.log(results);
})

// result
{
  data: { incrementArray: 6 },
  loading: false,
  networkStatus: 7,
  stale: false
}

const query = gql`
        {
            addition(param1: 6, param2: 19)
        }
    `
apolloClient.query({query}).then(results => {
    console.log(results);
})

// result
{
  data: { addition: 25 },
  loading: false,
  networkStatus: 7,
  stale: false
}
```
4. Calling the “increment” function results in an error both from Fauna dashboard playground and from javascript client application:
```
const query = gql`
        {
            increment(param1: 5)
        }
    `
apolloClient.query({query}).then(results => {
    console.log(results);
})

// throws an error
graphQLErrors: [
    {
      message: 'Number expected, Array provided.',
      extensions: { code: 'invalid argument' }
    }
  ],
  networkError: null,
  extraInfo: undefined
}
```

The functions "increment" and "incrementArray" are the same besides that the parameter is wrapped as an array for the last one. It looks like this issue is not related to the fauna driver, I'll send it to the Core team to take a look.

@guillaumervls So the workaround is, as you said, to wrap the input parameter of a function into an array as it is done in "incrementArray" even though it can be created without it.

**Comment by marrony** [comment]
Lambdas (and UDF) arguments works pretty much similar to javascript functions, if you define the arguments as an array, you are kinda exploding the values passed and capturing it in a named variables inside the body of the function.
```
function increment(x, y) {
  return x + y
}
```
```
Lambda(["x", "y"], Add(Var("x"), Var("y")))
```

However if you define a single argument, you are kinda capturing all the arguments in an array, like `arguments` variable in javascript.
```
function increment() {
  return arguments[0] + arguments[1]
}
```
```
Lambda("args", Add(Select(0, Var("args")), Select(1, Var("args"))))
```

**Comment by parkhomenko** [comment]
@marrony Thanks for the explanation. So it is done by design and it is just not correct to create a function with a single argument that is not wrapped as an array if I use GraphQL?
I mean I can run both functions as below and get correct results:
```
Call(Function("increment"), 5) // returns 6
Call(Function("incrementArray"), 5) // returns 6
```
Is there a way I can write GraphQL to make the first one "increment" work?
This graphql throws an error for the "increment" function but works for "incrementArray"
```
{
    increment(param1: 5)
}
```
Of course, if it is correct at all to use it.

**Comment by marrony** [comment]
there is no way to fix this on GraphGL, so my recommendation is use arrays while defining the arguments in the lambdas

**Comment by n400** [comment]
Thank you! We will make a docs ticket to help clarify this.
