### ISSUE TITLE
Custom fetch doesn't work per-query

### ISSUE THREAD

**Issue by hazae41** [fauna/faunadb-js#542]
When doing some debugs, I found that `client.query({ fetch: myfetch })` does not work, while `new Client({ fetch: myfetch })` works

```typescript
function myfetch(a, b) {
  console.log(a, b)
  return fetch(a, b)
}

// Works
const client = new Client({ secret, fetch: myfetch })
await client.query(query)

// Doesn't work, default fetch is used
const client = new Client({ secret })
await client.query(query, { fetch: myfetch })
```

**Comment by fireridlle** [comment]
hello @hazae41. if you would like to use a different `fetch` implementation, you need to create a different fauna client.
the reason behind why `fetch` doesn't work for client.query option, because we use http2 protocol whenever possible and fall back to http1 if http2 is not supported or fauna client constructor receives fetch option.
